references:
  gems-key: &gems-key
    gems-v2-{{ checksum "Gemfile.lock" }}

  save-gems-cache: &save-gems-cache
    save_cache:
      key: *gems-key
      paths:
        - vendor/bundle

  restore-gems-cache: &restore-gems-cache
    restore_cache:
      key: *gems-key

  download-ruby-dependencies: &download-ruby-dependencies
    run:
      name: Download Ruby dependencies
      command: make download-ruby-dependencies

  set-git-user: &set-git-user
    run:
      name: Set Git User
      command: |
        git config user.email $GIT_USER_EMAIL
        git config user.name $GIT_USER_NAME

version: 2.1
jobs:
  create-new-release:
    docker:
      - image: cimg/android:2023.06.1
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - *restore-gems-cache
      - *download-ruby-dependencies
      - *save-gems-cache
      - *set-git-user
      - add_ssh_keys:
          fingerprints:
            - "53:16:94:96:22:d7:aa:f8:ab:69:a3:44:8b:b0:37:ff"
      - run:
          name: Create new release
          command: make create-release

workflows:
  version: 2.1
  new-version:
    jobs:
      - create-new-release:
          filters:
            branches:
              only:
                - main
